In [4]:
#1. Create a null vector of size 7 but the third and last value as 2.
import numpy as np

null_v = np.zeros(7, dtype = np.int32)
null_v[2] = 2
null_v[-1] = 2
print(null_v)


[0 0 2 0 0 0 2]


In [48]:
#2. Create a vector of size 9 with values ranging from 0 to 2, both excluded.
vec = np.linspace(0, 2, 11, endpoint= True)[1:-1]
print(vec)

[0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]


In [10]:
#3. Convert the first character of each element in a series to uppercase? And return the new series - pandas
import pandas as pd
series = pd.Series(['romario', 'haaland', 'lautaro'])
new_series = series.str.capitalize()
print(new_series)


0    Romario
1    Haaland
2    Lautaro
dtype: object


In [12]:
#4. Given a 3*3 matrix named matrix_fab, From each element of this matrix subtract the mean of that row, name this
#matrix as matrix_sub. Divide each element of this matrix by twice of the largest element to get matrix_norm. Print it out.

import numpy as np
matrix_fab = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])
matrix_sub = matrix_fab - matrix_fab.mean(axis=1, keepdims=True)
matrix_norm = matrix_sub / (2 * np.max(matrix_sub))
print(matrix_norm)


[[-0.5  0.   0.5]
 [-0.5  0.   0.5]
 [-0.5  0.   0.5]]


In [26]:
#5. Create a random vector of size 12 , sort it in decreasing order, make 4*3 array using it.
random_v = np.random.rand(12)

random_v.sort()
random_v = random_v[::-1]
array = random_v.reshape(4, 3)
print(array)

[[0.89009992 0.85152899 0.68268681]
 [0.67266099 0.5751075  0.57295716]
 [0.42001591 0.14252268 0.1326987 ]
 [0.11126675 0.06373951 0.06127411]]


In [30]:
#6. Create a DataFrame df from dictionary data and select rows where the age is NaN.
import pandas as pd
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

df = pd.DataFrame(data)

missing_age = df[df['age'].isna()]
print(missing_age)

  animal  age  visits priority
3    dog  NaN       3      yes
7    cat  NaN       1      yes


In [32]:
#7 Modify df, update 'dog' to 'Labrador', change age of row 'd', and calculate mean_age.
df['animal'] = df['animal'].replace('dog', 'Labrador')
df.at['d', 'age'] = 2.7
mean_age = df.groupby('animal')['age'].mean()
print(df)
print("Mean Age:", mean_age)

     animal  age  visits priority
0       cat  2.5     1.0      yes
1       cat  3.0     3.0      yes
2     snake  0.5     2.0       no
3  Labrador  NaN     3.0      yes
4  Labrador  5.0     2.0       no
5       cat  2.0     3.0       no
6     snake  4.5     1.0       no
7       cat  NaN     1.0      yes
8  Labrador  7.0     2.0       no
9  Labrador  3.0     1.0       no
d       NaN  2.7     NaN      NaN
Mean Age: animal
Labrador    5.0
cat         2.5
snake       2.5
Name: age, dtype: float64


In [38]:
#8. Get the positions where values of two columns match in a DataFrame.

df_example = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [1, 1, 3, 2, 5]
})

matches = df_example[df_example['A'] == df_example['B']].index

print("Positions where columns match:", matches.tolist())

Positions where columns match: [0, 2, 4]


In [42]:
 # Q9.Find the positions of numbers that are multiples of 4 from a series.
series = pd.Series([1, 4, 6, 8, 12, 15, 16, 20, 23, 24])
positions = series[series % 4 == 0].index
print("Positions of multiples of 4:", positions.tolist())

Positions of multiples of 4: [1, 3, 4, 6, 7, 9]


In [44]:
# Q10. Stack two given series vertically and horizontally.
series1 = pd.Series([11, 27, 34])
series2 = pd.Series([42, 95, 76])


vertical = pd.concat([series1, series2], axis=0)
horizontal = pd.concat([series1, series2], axis=1)

print("Vertical Stack:\n", vertical)
print("Horizontal Stack:\n", horizontal)

Vertical Stack:
 0    11
1    27
2    34
0    42
1    95
2    76
dtype: int64
Horizontal Stack:
     0   1
0  11  42
1  27  95
2  34  76
