In [4]:
import numpy as np
import pandas as pd

In [8]:
#Q1: Form a 1D array containing elements from -2 (including) to 10 (excluding) in arithmetic progression, negate all elements between 2 and 7.
a = np.arange(-2,10,1.5)
def negarr(x):
    x[(x>2) & (x<7)] *= -1
    print('Negated array: ', x)
negarr(a)

Negated array:  [-2.  -0.5  1.  -2.5 -4.  -5.5  7.   8.5]


In [20]:
# Q2 Create a random vector of size 7 and replace the maximum value with 2 and the minimum with 7. Sort this array in reverse order.

x = np.random.rand(7)
def edit(a):
    a[a.argmax()] = 2
    a[a.argmin()] = 7
    a = np.sort(a)[::-1]
    print(a)
edit(x)

[7.         2.         0.76008183 0.75881784 0.62905887 0.44194208
 0.3092889 ]


In [22]:
#Q3. Convert a random 7x2 matrix (representing cartesian coordinates) to polar coordinates.

cartesian_coords = np.random.rand(7, 2)
r = np.sqrt(cartesian_coords[:, 0]**2 + cartesian_coords[:, 1]**2)
theta = np.arctan2(cartesian_coords[:, 1], cartesian_coords[:, 0])
print("Cartesian Coordinates:\n", cartesian_coords)
print("Polar Coordinates (r, theta):\n", np.column_stack((r, theta)))

Cartesian Coordinates:
 [[0.24258121 0.38105461]
 [0.15789089 0.32514457]
 [0.36564389 0.07617523]
 [0.70449335 0.17281552]
 [0.41881232 0.45221311]
 [0.14589677 0.65901658]
 [0.29218185 0.31707946]]
Polar Coordinates (r, theta):
 [[0.45171701 1.00389544]
 [0.36145335 1.11873323]
 [0.37349447 0.20539388]
 [0.72537996 0.24055469]
 [0.61636065 0.8237259 ]
 [0.67497313 1.35292479]
 [0.43117237 0.82624068]]


In [24]:
#Q4. Create a numpy array sequence with given start, step size, and length.

def create_arr(start,step,length):
    return np.arange(start, start + step*length, step)

arr = create_arr(10,2,8)
print(arr)

[10 12 14 16 18 20 22 24]


In [28]:
#Q5. Make a 3x3 array from evenly spaced numbers, transpose it, and subtract a 1x3 array of ones.

a1 = np.linspace(1,10,9)
a2 = a1.reshape(3,3)
a3 = a2.T
a4 = a3 - np.ones((1,3))

print('Original matrix:\n', a2)
print('Transpose: \n', a3)
print('Subt Result: \n', a4)

Original matrix:
 [[ 1.     2.125  3.25 ]
 [ 4.375  5.5    6.625]
 [ 7.75   8.875 10.   ]]
Transpose: 
 [[ 1.     4.375  7.75 ]
 [ 2.125  5.5    8.875]
 [ 3.25   6.625 10.   ]]
Subt Result: 
 [[0.    3.375 6.75 ]
 [1.125 4.5   7.875]
 [2.25  5.625 9.   ]]


In [30]:
#Q6. Create a DatetimeIndex containing business days of 2016 and use it to index a Series of random numbers.

days = pd.date_range(start = '2016-01-01', end = '2016-12-31', freq = 'B')

bus_2k16 = pd.Series(np.random.randn(len(days)), index = days)
print(bus_2k16)

2016-01-01    0.794868
2016-01-04   -0.351796
2016-01-05   -1.043909
2016-01-06   -0.522578
2016-01-07    0.058772
                ...   
2016-12-26   -0.813083
2016-12-27   -0.527356
2016-12-28   -0.641716
2016-12-29   -2.031435
2016-12-30   -1.730670
Freq: B, Length: 261, dtype: float64


In [32]:
#Q7. For each calendar month in bus_2k16, find the mean and sum of values for Sundays.

monthly_mean = bus_2k16.resample('M').mean()

sundays_sum = bus_2k16[bus_2k16.index.weekday == 6].resample('W-SUN').sum()

print("Monthly Mean:\n", monthly_mean)
print("Sum of values on Sundays:\n", sundays_sum)

Monthly Mean:
 2016-01-31    0.286685
2016-02-29   -0.087661
2016-03-31    0.125482
2016-04-30    0.404862
2016-05-31    0.106641
2016-06-30   -0.134998
2016-07-31   -0.087443
2016-08-31   -0.013744
2016-09-30    0.046176
2016-10-31   -0.260893
2016-11-30   -0.055757
2016-12-31   -0.165112
Freq: M, dtype: float64
Sum of values on Sundays:
 Series([], Freq: W-SUN, dtype: float64)


In [34]:
#Q8. Split the From_To column in df and standardize the strings.
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                              'Budapest_PaRis', 'Brussels_londOn'],
                  'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
                  'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                  'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                              '12. Air France', '"Swiss Air"']})

temp = df['From_To'].str.split('_', expand = True)
temp.columns = ['From','To']
temp['From'] = temp['From'].str.capitalize()
temp['To'] = temp['To'].str.capitalize()
print(temp)

       From         To
0    London      Paris
1    Madrid      Milan
2    London  Stockholm
3  Budapest      Paris
4  Brussels     London


In [36]:
#Q9. Find the column with the smallest sum and count the number of unique rows in the DataFrame.

df = pd.DataFrame(np.random.rand(100, 10), columns=[f'col{i}' for i in range(10)])
smallest_sum_column = df.sum().idxmin()
unique_rows_count = df.drop_duplicates().shape[0]

print("Column with smallest sum:", smallest_sum_column)
print("Number of unique rows:", unique_rows_count)

Column with smallest sum: col7
Number of unique rows: 100


In [38]:
#Q 10. Filter out rows where the 'int' column has the same value as the row above and subtract the mean.

df = pd.DataFrame({'int': [1, 2, 2, 3, 3, 3, 4, 5, 5, 6]})


df_filtered = df[df['int'] != df['int'].shift()]
df_subt = df - df['int'].mean()

print("Filtered DataFrame:\n", df_filtered)
print("DataFrame after subtracting the mean:\n", df_subt)

Filtered DataFrame:
    int
0    1
1    2
3    3
6    4
7    5
9    6
DataFrame after subtracting the mean:
    int
0 -2.4
1 -1.4
2 -1.4
3 -0.4
4 -0.4
5 -0.4
6  0.6
7  1.6
8  1.6
9  2.6
