In [2]:
import numpy as np
import pandas as pd

In [ ]:
#Q1. Find all the indices of peaks in a 1D numpy array.
n = np.array([2, 7, 1, 3, 7, 1, 2, 6, 0, 1, 3, 7, 6])
arr = []
i = 1
while i < len(n)-1:
    if n[i] > n[i-1] and n[i] > n[i+1]:
        arr.append(i)
        i += 1
print (arr)

In [8]:
#Q2. Create an 8x8 chessboard pattern matrix.
board = np.zeros((8,8), dtype = int)
board[1::2, ::2] = 1
board[::2, 1::2] = 1
print(board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [14]:
#Q3. Perform One-Hot Encoding
from sklearn.preprocessing import OneHotEncoder
import numpy as np

arr = np.array([0, 1, 2, 3, 1, 2])
encoder = OneHotEncoder(sparse = False)
one_hot = encoder.fit_transform(arr.reshape(-1, 1))

print( one_hot)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [18]:
#Q4. Display all dates for April 1994 and check weekdays.

import pandas as pd

dates = pd.date_range(start='1994-04-01', end='1994-04-30')
weekdays_c = (dates.weekday < 5).sum()
is_weekday = pd.Timestamp('1994-04-07').weekday() < 5

print("Dates in April 1994:\n", dates)
print("Number of weekdays:", weekdays_c)
print("Was 7th April 1994 a weekday?", is_weekday)

Dates in April 1994:
 DatetimeIndex(['1994-04-01', '1994-04-02', '1994-04-03', '1994-04-04',
               '1994-04-05', '1994-04-06', '1994-04-07', '1994-04-08',
               '1994-04-09', '1994-04-10', '1994-04-11', '1994-04-12',
               '1994-04-13', '1994-04-14', '1994-04-15', '1994-04-16',
               '1994-04-17', '1994-04-18', '1994-04-19', '1994-04-20',
               '1994-04-21', '1994-04-22', '1994-04-23', '1994-04-24',
               '1994-04-25', '1994-04-26', '1994-04-27', '1994-04-28',
               '1994-04-29', '1994-04-30'],
              dtype='datetime64[ns]', freq='D')
Number of weekdays: 21
Was 7th April 1994 a weekday? True


In [20]:
#Q5. Create a 5x5 array with 1 on the border and 2 inside, pad with a border of 7's.

arr = np.ones((5, 5)) * 2  #2s inside
arr[0, :] = arr[:, 0] = arr[-1, :] = arr[:, -1] = 1  #border of 1s

padded_arr = np.pad(arr, pad_width=2, mode='constant', constant_values=7) #padding of 7
inner_product = np.inner(padded_arr, padded_arr)

print("Padded array:\n", padded_arr)
print("Inner product of the array:\n", inner_product)


Padded array:
 [[7. 7. 7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 1. 1. 1. 1. 1. 7. 7.]
 [7. 7. 1. 2. 2. 2. 1. 7. 7.]
 [7. 7. 1. 2. 2. 2. 1. 7. 7.]
 [7. 7. 1. 2. 2. 2. 1. 7. 7.]
 [7. 7. 1. 1. 1. 1. 1. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7. 7. 7.]]
Inner product of the array:
 [[441. 441. 231. 252. 252. 252. 231. 441. 441.]
 [441. 441. 231. 252. 252. 252. 231. 441. 441.]
 [231. 231. 201. 204. 204. 204. 201. 231. 231.]
 [252. 252. 204. 210. 210. 210. 204. 252. 252.]
 [252. 252. 204. 210. 210. 210. 204. 252. 252.]
 [252. 252. 204. 210. 210. 210. 204. 252. 252.]
 [231. 231. 201. 204. 204. 204. 201. 231. 231.]
 [441. 441. 231. 252. 252. 252. 231. 441. 441.]
 [441. 441. 231. 252. 252. 252. 231. 441. 441.]]


In [ ]:
#Q6. Count the difference back to the previous 7 (or the start).
df = pd.DataFrame({'int': [7, 2, 0, 7, 4, 2, 5, 7, 3, 5]})
df1 = df
df1['shift'] = df1['int'].shift(7)
startVal = df1['int'][0]
df1 = df1.fillna(startVal)
print (df1)
df1['A'] = df1['int'] - df1['shift']
print(df1['A'])

In [30]:
#Q7. Join dfs and perform merges

raw_data_1 = {'subject_id': ['1', '2', '3', '4', '5'], 'first_name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'], 'last_name': ['Anderson', 'Ackerman', 'Ali', 'Aoni', 'Atiches']}
raw_data_2 = {'subject_id': ['4', '5', '6', '7', '8'], 'first_name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'], 'last_name': ['Bonder', 'Black', 'Balwner', 'Brice', 'Btisan']}
raw_data_3 = {'subject_id': ['1', '2', '3', '4', '5', '7', '8', '9', '10', '11'], 'test_id': [51, 15, 15, 61, 16, 14, 15, 1, 61, 16]}

data1 = pd.DataFrame(raw_data_1)
data2 = pd.DataFrame(raw_data_2)
data3 = pd.DataFrame(raw_data_3)

data_all_row = pd.concat([data1, data2])
merge1 = pd.merge(data_all_row, data3, on='subject_id')
merge2 = pd.merge(data1, data2, how='outer')

print("Merged data (merge1):\n", merge1)
print("Outer merge (merge2):\n", merge2)


Merged data (merge1):
   subject_id first_name last_name  test_id
0          1       Alex  Anderson       51
1          2        Amy  Ackerman       15
2          3      Allen       Ali       15
3          4      Alice      Aoni       61
4          4      Billy    Bonder       61
5          5     Ayoung   Atiches       16
6          5      Brian     Black       16
7          7      Bryce     Brice       14
8          8      Betty    Btisan       15
Outer merge (merge2):
   subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches
5          4      Billy    Bonder
6          5      Brian     Black
7          6       Bran   Balwner
8          7      Bryce     Brice
9          8      Betty    Btisan


In [ ]:
#Q8. Analyzing the army dataframe

raw_data = {
    'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'],
    'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd'],
    'deaths': [523, 52, 25, 616, 43, 234, 523, 62, 62, 73, 37, 35],
    'veterans': [1, 5, 62, 26, 73, 37, 949, 48, 48, 435, 63, 345],
    'origin': ['Arizona', 'California', 'Texas', 'Florida', 'Maine', 'Iowa', 'Alaska', 'Washington', 'Oregon', 'Wyoming', 'Louisana', 'Georgia']
}

df = pd.DataFrame(raw_data)
df.set_index('origin', inplace=True)
total_veterans = df['veterans'].sum()
deaths_filter = df[(df['deaths'] > 450) | (df['deaths'] < 45)]
non_dragoons = df[df['regiment'] != 'Dragoons']
texas_arizona = df.loc[['Texas', 'Arizona']]
fifth_cell = df.loc['Texas'].iloc[:,4]

print("Total veterans:", total_veterans)
print("Rows where deaths > 450 or deaths < 45:\n", deaths_filter)
print("Non-Dragoons:\n", non_dragoons)
print("Texas and Arizona:\n", texas_arizona)
print("Fifth cell in Texas row:", fifth_cell)

In [38]:
#Q9. Filter and capitalize words with at least 2 vowels

series = pd.Series(['Insaid', 'strives', 'for', 'bringing', 'out', 'the', 'best', 'in', 'you'])
vowel_filtered = series[series.str.count(r'[aeiouAEIOU]') >= 2].str.upper()

print("Words with at least 2 vowels capitalized: ", vowel_filtered)

Words with at least 2 vowels capitalized:  0      INSAID
1     STRIVES
3    BRINGING
4         OUT
8         YOU
dtype: object


In [40]:
#Q 10. Create a dataframe from a 4*4 array containing elements from 0 to15 in a squential order. Swap rows third
#and fourth by creating a generic function to swap two rows. Now print the dataframe obtained after reversing the
#elements of each column.

df = pd.DataFrame(np.arange(16).reshape(4, 4))

def swap_rows(df, row1, row2):
    df.iloc[[row1, row2]] = df.iloc[[row2, row1]]

swap_rows(df, 2, 3)
df_reversed = df.apply(lambda col: col[::-1])

print("DataFrame after swapping rows and reversing columns:\n", df_reversed)

DataFrame after swapping rows and reversing columns:
     0   1   2   3
3   8   9  10  11
2  12  13  14  15
1   4   5   6   7
0   0   1   2   3
